### ISSUE TITLE
The new version doesn't accept the data sent by competitive companion

### ISSUE THREAD

**Issue by muhammad-sayed-mahdy** [mfornet/acmx#100]
There is a bug in the new version. When I use competitive companion on windows 10, it doesn't open the problem on vscode
The previous version (0.3.3) is working fine with me

**Comment by mfornet** [comment]
@muhammad-sayed-mahdy it is working ok for me on 0.3.4. I tried with a [problem from codeforces](https://codeforces.com/problemset/problem/1374/B).

One possible problem is if you updated to latest (or w/e) version you probably need to restart vscode, since it starts a server in background listening for competitive-companion requests and probably it was not up. Notice also if you have several vscode instance open the server will be working in at most one of the instances.

Can you try upgrading to v0.3.4, restart vscode, and try again.

If that didn't help, can you provide more information, like link to problem it is failing for you, and competitive companion version.

**Comment by muhammad-sayed-mahdy** [comment]
I upgraded to v0.3.4 then restarted vscode, and tried using [the same problem](https://codeforces.com/problemset/problem/1374/B) you provided and the issue still exists
competitive companion version: 2.17.1

**Comment by Salil03** [comment]
I think https://github.com/mfornet/acmx/commit/d493f4cb30bb249a7beb947e179307dc1e345fed should fix it. @muhammad-sayed-mahdy Can you check if this bug is still present?

**Comment by muhammad-sayed-mahdy** [comment]
Yes, fixed thanks
