### ISSUE TITLE
Unable to parse problem with double quotes in its name

### ISSUE THREAD

**Issue by NotchApple1703** [mfornet/acmx#152]
Im trying to parse contest: [1984](https://codeforces.com/contest/1984/) but the problem D isn't parsed
I tried to parsed it individually but it doesn't work either

![image](https://github.com/mfornet/acmx/assets/96767159/bd789884-6ae3-4872-bf1e-0176a939719a)

**Comment by mfornet** [comment]
It works for me on Mac, using Competitive Companion `2.53.0`.

After looking around for a bit, I noticed that the problem is that Windows doesn't allow double quotes in folder names [source](https://stackoverflow.com/a/52618372/4950797). 

A workaround to this problem is replacing invalid characters received from the extension. If you (or anybody else) is willing to contribute, it should be an easy change:

https://github.com/mfornet/acmx/blob/master/src/companion.ts#L52
In the previous linked line we are parsing data received from companion extension, we can check if we are on windows and remove double quotes from the name of the problem, or replace them by some other sensible character (in this case single quotes could work).

See the complete lists of unallowed characters in Windows: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions
