### ISSUE TITLE
Submit from acmx

### ISSUE THREAD

**Issue by mfornet** [mfornet/acmx#35]
New command to submit solutions directly from acmx.

The idea is using a web browser extension that spawns a server and is listening for new solutions to be submitted. This way, if the extension is already logged in in the website then should be easy to make the submission.

Maybe use the competitive-companion tool or create a brand new extension.

Relevant link: https://developer.chrome.com/apps/sockets_tcpServer

**Comment by Salil03** [comment]
I suggest you close this issue because to implement this for each site would be incredibly difficult. Or at least give this issue low priority as even implementing this for a single site(like codeforces) has many headaches. Some problems may be 

Codechef doesn't even allow multiple logins
Password encryption and all those things
Every website has unique submission path. There is no unified extension like competitive companion for this.
Some tools are already made for this made they only work for codeforces, so this suggests that it may be difficult for other websites.

**Comment by mfornet** [comment]
Actually my idea is to start an extension similar to competitive companion that initially works with Codeforces, and allows external tools like **acmX** to make automatic submissions. I agree that this issue in general is out of the scope of this tool, but I'll leave it to keep track of it.

**Comment by mfornet** [comment]
It seems to be done in this tool for codeforces: https://github.com/ahmed-dinar/codeforces-cli

**Comment by Salil03** [comment]
https://github.com/online-judge-tools/api-client this would help in submitting to more judges.

**Comment by mfornet** [comment]
Any custom tool can be used for automatic submission after implementation in #117
