### ISSUE TITLE
Any possibility of adding support to WSL

### ISSUE THREAD

**Issue by rashedmyt** [mfornet/acmx#7]

**Comment by rashedmyt** [comment]
Windows Subsystem for Linux

**Comment by mfornet** [comment]
@rashedmyt I expect this extension to be cross platform, but is really hard to me at the moment giving support for other platforms. I made most of the tests on Ubuntu 18.04, and have VirtualBox with Windows 10 to debug issues that might arise. If you report any particular issue I can reproduce in Windows 10, I'll try to fix it, otherwise I'll appreciate help from others to extend support for other platforms.

**Comment by rashedmyt** [comment]
If the server is starting at `localhost:10042` then WSL won't work.. it needs to start at `0.0.0.0:10042` to receive the POST requests from extension.

**Comment by rashedmyt** [comment]
Sorry.. I think its my fault.. Looks like I have misconfigured some options
